name: OpenSSF Scorecard
on:
  schedule:
    - cron: "0 4 * * 1"
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
      issues: read
      checks: read
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Run analysis
        uses: ossf/scorecard-action@55891bbd73f2425e97637d96e306fc9d491d0b21
        with:
          results_file: results.sarif
          results_format: sarif
          publish: true
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@6d786de4d6f3531a740e445b53a42b622bbbace8
        with:
          sarif_file: results.sarif
